### DISCUSSION TITLE
ra-tls-secret-prov/secret_prov_pf on Kubernetes not decrypting file (no errors apparently)

### DISCUSSION THREAD

**Discussion by tiagorvmartins** [gramineproject/gramine#1610] [Q&A] [answered]
Hello, I am trying to run the example [ra-tls-secret-prov/secret_prov_pf](https://github.com/gramineproject/gramine/tree/master/CI-Examples/ra-tls-secret-prov/secret_prov_pf) on a kubernetes environment using volumes with encrypted mounts on gsc manifest - sorry if its the wrong place to make this question.

The client and the server were ported to a docker image, to make it easier to run on kubernetes.
The client image was graminized with the following manifest:

```
sys.enable_sigterm_injection = true

sgx.remote_attestation = "dcap"

sys.stack.size = "16M"
sys.enable_extra_runtime_domain_names_conf = true
sys.experimental__enable_flock = true
sgx.nonpie_binary = true
sgx.enclave_size = "512M"
sgx.edmm_enable = false
sgx.max_threads = 32

fs.mounts = [
  { path = "/files/", uri = "file:/files/",  type = "encrypted" }
]

sgx.trusted_files = [
  "file:/app/client",
  "file:/etc/host.conf",
  "file:/etc/hosts",
  "file:/etc/nsswitch.conf",
  "file:/etc/resolv.conf",
  "file:/serv_prov/ssl/ca.crt"
]

loader.env.TZ = ":/etc/localtime"
loader.env.SGX_AESM_ADDR="1"
loader.env.LD_PRELOAD = "libsecret_prov_attest.so"
loader.env.SECRET_PROVISION_CONSTRUCTOR = "1"
loader.env.SECRET_PROVISION_SET_KEY = "default"
loader.env.SECRET_PROVISION_CA_CHAIN_PATH = "/serv_prov/ssl/ca.crt"
loader.env.SECRET_PROVISION_SERVERS = "secretprovisioning:4433"
```

Here is the kubernetes yml file, where I encrypt the file (on a init container called encrypt-data) using the volume and then use the same encrypted file on the main container called client - attaching the same volume.

```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sgx-client
  namespace: testing
  labels:
    app: sgx-client
spec:
  serviceName: sgx-client
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: sgx-client
  template:
    metadata:
      labels:
        app: sgx-client
    spec:
      containers:
      - name: client
        resources:
          limits:
            sgx.intel.com/epc: "1Mi"
        image: tiagorvmartins/sgx-client-test
        imagePullPolicy: Always
        volumeMounts:
        - name: data
          mountPath: /files/        
        - name: aesmd
          mountPath: /var/run/aesmd        
      initContainers:
      - name: encrypt-data
        image: gramineproject/gramine
        command: ["/bin/sh"]
        args:
        - "-c"
        - |
          if [ -d /files/input.txt ]
          then
            echo 'Data already encrypted.'
            exit 0;
          else            
            echo 'Hi! this is a test!' > /files/input.txt
            echo 'Cat on file content:'
            cat /files/input.txt            
            echo -n $ENCRYPT_KEY | base64 -d > wrap_key            
            gramine-sgx-pf-crypt encrypt -w wrap_key -i /files/input.txt -o /files/input.txt            
            exit 0;
          fi;          
        env:
        - name: ENCRYPT_KEY
          valueFrom:
            secretKeyRef:
              name: secretprovisioning
              key: encrypt_key
        volumeMounts:
        - name: data
          mountPath: /files/
      volumes:  
        - name: aesmd
          hostPath:
            path: /var/run/aesmd 
      nodeSelector:
        kubernetes.azure.com/agentpool: testing
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: default
      resources:
        requests:
          storage: 500Gi
```

And here are the logs of the server that provides the secret:

```
--- Reading the master key for encrypted files from '/server/wrap_key' ---
--- Starting the Secret Provisioning server on port 4433 ---Azure Quote Provider: libdcap_quoteprov.so [ERROR]: Could not retrieve environment variable for 'AZDCAP_DEBUG_LOG_LEVEL'
WARNING: The collateral is out of date.
Received the following measurements from the client:  - MRENCLAVE:   082f2c9dafa3c2833119c6719b46d863046624ee409ab15d648176f213e88d80
  - MRSIGNER:    3d83d1e4a46aeaa9c0958026cdb402628e026fd6c08a0bb57c98445a423cc22a
  - ISV_PROD_ID: 0
  - ISV_SVN:     0
[ WARNING: In reality, you would want to compare against expected values! ]
```

And here is the logs of the client container:
```
Gramine is starting. Parsing TOML manifest file, this may take some time...
-----------------------------------------------------------------------------------------------------------------------
Gramine detected the following insecure configurations:

  - loader.insecure__use_cmdline_argv = true   (forwarding command-line args from untrusted host to the app)
  - sys.experimental__enable_flock = true      (flock syscall is enabled; still under development and may contain bugs)

Gramine will continue application execution, but this configuration must not be used in production!
-----------------------------------------------------------------------------------------------------------------------

--- [main] Re-starting myself using execvp() ---
--- [child] Read from protected file: 'GRAFS_PF' ---
--- [parent] Read from protected file: 'GRAFS_PF' ---
```

Since it shows 'GRAFS_PF' its not actually decrypting the file, it is instead the encrypted file itself...
I thought this was a transparent operation, since the manifest marked this folder as encrypted. 
I was expecting to read: "Hi! this is a test!"

I guess the problem is related to how kubernetes handles this kind of volumes.
Any thoughts on what I might be doing wrong?
Let me know if you need any extra information.

Thank you in advance!
