### ISSUE TITLE
Heap corruption detected: invalid heap level 239

### ISSUE THREAD

**Issue by alexander-lindner** [gramineproject/gramine#538]
## Description of the problem
I have a python script running inside Gramine, which fails to connect via a tls socket to a server. Python 3.10.
I don't know what `shim_connect` does and therefore, I don't know what's the problem and what I have done wrong.

The last lines of the log:
```
[P1:T1:python3.10] trace: ---- shim_openat(AT_FDCWD, "/misc/keys/public/client_enclave.cert", O_RDONLY, 0000) = 0x4
[P1:T1:python3.10] trace: ---- shim_newfstatat(4, "", 0x105c0cc00, 4096) = 0x0
[P1:T1:python3.10] trace: ---- shim_read(4, 0x4454c530, 0x2000) ...
[P1:T1:python3.10] trace: ---- return from shim_read(...) = 0x41e
[P1:T1:python3.10] trace: ---- shim_read(4, 0x4454c530, 0x2000) ...
[P1:T1:python3.10] trace: ---- return from shim_read(...) = 0x0
[P1:T1:python3.10] trace: ---- shim_close(4) = 0x0
debug: load_protected_file: misc/keys/private/client_enclave.key, fd 99, size 4096, mode 1, create 0, pf 0x3f7358a30
debug: load_protected_file: misc/keys/private/client_enclave.key, fd 99: opening new PF 0x3f7358a30
[P1:T1:python3.10] trace: ---- shim_openat(AT_FDCWD, "/misc/keys/private/client_enclave.key", O_RDONLY, 0000) = 0x4
[P1:T1:python3.10] trace: ---- shim_newfstatat(4, "", 0x105c0c7f0, 4096) = 0x0
[P1:T1:python3.10] trace: ---- shim_read(4, 0x4454c530, 0x2000) ...
[P1:T1:python3.10] trace: ---- return from shim_read(...) = 0x68f
[P1:T1:python3.10] trace: ---- shim_close(4) = 0x0
[P1:T1:python3.10] trace: ---- shim_getsockopt(3, 1, 3, 0x105c0cc08, 0x105c0cc0c) = 0x0
[P1:T1:python3.10] trace: ---- shim_getsockname(3, 0x105c0c880, 0x105c0c86c) = 0x0
[P1:T1:python3.10] trace: ---- shim_ioctl(3, FIONBIO, 0x105c0cc1c) ...
[P1:T1:python3.10] trace: ---- return from shim_ioctl(...) = 0x0
[P1:T1:python3.10] trace: ---- shim_getpeername(3, 0x105c0cb90, 0x105c0cb8c) = -107
[P1:T1:python3.10] trace: ---- shim_bind(3, 0x105c0d1f0, 16) = 0x0
[P1:T1:python3.10] trace: ---- shim_clock_gettime(0, 0x105c0c620) = 0x0
[P1:T1:python3.10] trace: ---- shim_getpid() = 0x1
[P1:T1:python3.10] trace: ---- shim_write(2, 0x1050c2db0, 0x59) ...
09:38:16.471 [   root] CommunicationClient INFO: Connecting to server at 127.0.0.1:44000
[P1:T1:python3.10] trace: ---- return from shim_write(...) = 0x59
[P1:T1:python3.10] trace: ---- shim_connect(3, {family=INET,ip=127.0.0.1,port=htons(44000)}, 16) ...
[P1:T1:python3.10] Heap corruption detected: invalid heap level 239
debug: DkProcessExit: Returning exit code 1
make: *** [Makefile:32: rerunClient] Error 1
```

## Steps to reproduce
My Python Code:
```python
socketClient = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
socketClient.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)

sslSocketClient: SSLSocket = ssl.wrap_socket(
    socketClient,
    server_side=False,
    keyfile=self.key,
    certfile=self.cert,
)

sslSocketClient.bind((self.host, self.port - (10000 if not self.enclave else 20000) + 1))
logging.info("Connecting to server at {0}:{1}".format(self.host, self.port))
sslSocketClient.connect((self.host, self.port))
```
The manifest file:
```toml
[loader]
entrypoint = "file:/usr/lib/x86_64-linux-gnu/gramine/libsysdb.so"
log_level = "all"
insecure__use_cmdline_argv = true
insecure__use_host_env = true
pal_internal_mem_size = "256M"
preload = ""

[libos]
entrypoint = "utils/libs/python-install-dir/bin/python3.10"

[sys]
enable_sigterm_injection = true

[sgx]
nonpie_binary = true
enclave_size = "16G"
thread_num = 256
debug = false
isvprodid = 2
isvsvn = 2
remote_attestation = true
ra_client_spid = ""
insecure__protected_files_key = "ffeeddccbbaa99887766554433221100"
protected_mrsigner_files = [ "file:misc/keys/private/",]
allowed_files = [ "file:misc/keys/public", "file:./logs/",]
require_avx = false
require_avx512 = false
require_mpx = false
require_pkru = false
require_amx = false
support_exinfo = false
enable_stats = false
[[sgx.trusted_files]]
uri = "file:/usr/lib/x86_64-linux-gnu/gramine/libsysdb.so"

[[sgx.trusted_files]]
uri = "file:utils/libs/python-install-dir/bin/python3.10"

[[sgx.trusted_files]]
uri = "file:/usr/lib/x86_64-linux-gnu/gramine/runtime/glibc/"

[[sgx.trusted_files]]
uri = "file:/lib/x86_64-linux-gnu/"

[[sgx.trusted_files]]
uri = "file:/usr//lib/x86_64-linux-gnu/"

[[sgx.trusted_files]]
uri = "file:./utils/"

[[sgx.trusted_files]]
uri = "file:./EnclaveMain.py"

[[sgx.trusted_files]]
uri = "file:./client.config"

[[sgx.trusted_files]]
uri = "file:./__init__.py"

[[sgx.trusted_files]]
uri = "file:./node.manifest"

[[sgx.trusted_files]]
uri = "file:./lib/"

[[sgx.trusted_files]]
uri = "file:/usr/lib/ssl/openssl.cnf"

[loader.env]
LD_LIBRARY_PATH = "/lib:/usr/lib:/lib/x86_64-linux-gnu:/usr//lib/x86_64-linux-gnu:utils/libs/python-install-dir/lib:utils/libs/libffi/lib"
PYTHONHOME = "utils/libs/python-install-dir"
PYTHONPATH = "/:/app/"
PYTHONDONTWRITEBYTECODE = "1"

[fs.mount.lib]
type = "chroot"
path = "/lib"
uri = "file:/usr/lib/x86_64-linux-gnu/gramine/runtime/glibc"

[fs.mount.lib2]
type = "chroot"
path = "/lib/x86_64-linux-gnu"
uri = "file:/lib/x86_64-linux-gnu"

[fs.mount.usr]
type = "chroot"
path = "/usr"
uri = "file:/usr"

[fs.mount.app]
type = "chroot"
path = "/app/"
uri = "file:./"

```
## Gramine commit hash
v1.1 Ubuntu Repo
```
Package: gramine
Version: 1.1-1
```
