### ISSUE TITLE
RA: [get_driver_type /mnt/linux-sgx/psw/urts/linux/edmm_utility.cpp:111] Failed to open Intel SGX device.

### ISSUE THREAD

**Issue by alexander-lindner** [gramineproject/gramine#571]
## Description of the problem
I want to verify my quote using `sgx_qv_verify_quote` inside a sgx gramine enclave, which fails:
```
[get_driver_type edmm_utility.cpp:111] Failed to open Intel SGX device.
[get_driver_type /mnt/linux-sgx/psw/urts/linux/edmm_utility.cpp:111] Failed to open Intel SGX device.
[get_driver_type edmm_utility.cpp:111] Failed to open Intel SGX device.
[get_driver_type /mnt/linux-sgx/psw/urts/linux/edmm_utility.cpp:111] Failed to open Intel SGX device.
```
The code runs perfectly fine with gramine-direct. 
Because gramine [also uses](https://github.com/gramineproject/gramine/blob/0c43b4275bb90932fbf228a68411a98c78d7c3cd/Pal/src/host/Linux-SGX/tools/ra-tls/ra_tls_verify_dcap.c#L138)  `sgx_qv_verify_quote` for the ra-tls stuff, I tried to build the [Example](https://github.com/gramineproject/gramine/tree/master/CI-Examples/ra-tls-mbedtls), which also fails:
```
[ using our own SGX-measurement verification callback (via command line options) ]
  - ignoring ISV_PROD_ID
  - ignoring ISV_SVN

  . Seeding the random number generator... ok
  . Connecting to tcp/localhost/4433... ok
  . Setting up the SSL/TLS structure... ok
  . Loading the CA root certificate ... ok
  . Performing the SSL/TLS handshake... ok
  . Installing RA-TLS callback ... ok
  . Performing the SSL/TLS handshake...[get_driver_type edmm_utility.cpp:111] Failed to open Intel SGX device.
[get_driver_type /mnt/linux-sgx/psw/urts/linux/edmm_utility.cpp:111] Failed to open Intel SGX device.
[get_driver_type edmm_utility.cpp:111] Failed to open Intel SGX device.
[get_driver_type /mnt/linux-sgx/psw/urts/linux/edmm_utility.cpp:111] Failed to open Intel SGX device.
 failed
  ! mbedtls_ssl_handshake returned -30592

Last error was: -30592 - SSL - A fatal alert message was received from our peer

  . Waiting for a remote connection ... failed
  ! mbedtls_ssl_handshake returned -0x3000

Last error was: -12288 - X509 - A fatal error occurred, eg the chain is too long or the vrfy callback failed
```
Unfortunately, the non-sgx commands from the example also fail:
```
[ using default SGX-measurement verification callback (via RA_TLS_* environment variables) ]

  . Seeding the random number generator... ok
  . Connecting to tcp/localhost/4433... ok
  . Setting up the SSL/TLS structure... ok
  . Loading the CA root certificate ... ok
  . Performing the SSL/TLS handshake... ok
  . Installing RA-TLS callback ... ok
  . Performing the SSL/TLS handshake...verify_quote_body_enclave_attributes: Quote: DEBUG bit in enclave attributes is set
 failed
  ! mbedtls_ssl_handshake returned -0x3000

Last error was: -12288 - X509 - A fatal error occurred, eg the chain is too long or the vrfy callback failed

 failed
  ! mbedtls_ssl_handshake returned -30592

Last error was: -30592 - SSL - A fatal alert message was received from our peer

  . Waiting for a remote connection ...%  
```
Mounting sgx devs into gramine like the error code mentions makes obviously no sense so how do I fix this error?

## Manifest
`$ cat client_dcap.manifest `:
```toml
[loader]
entrypoint = "file:/usr/local/lib/x86_64-linux-gnu/gramine/libsysdb.so"
log_level = "error"
insecure__use_cmdline_argv = true
insecure__use_host_env = true

[libos]
entrypoint = "client"

[fs]
[[fs.mounts]]
path = "/lib"
uri = "file:/usr/local/lib/x86_64-linux-gnu/gramine/runtime/glibc"

[[fs.mounts]]
path = "/lib/x86_64-linux-gnu"
uri = "file:/lib/x86_64-linux-gnu"

[[fs.mounts]]
path = "/usr/lib/x86_64-linux-gnu"
uri = "file:/usr/lib/x86_64-linux-gnu"

[[fs.mounts]]
path = "/etc"
uri = "file:/etc"

[sgx]
debug = true
remote_attestation = true
enclave_size = "256M"
thread_num = 4
allowed_files = [ "file:/etc/nsswitch.conf", "file:/etc/host.conf", "file:/etc/resolv.conf", "file:/etc/ethers", "file:/etc/hosts", "file:/etc/group", "file:/etc/passwd", "file:/etc/gai.conf", "file:/etc/ssl/certs/ca-certificates.crt", "file:/etc/sgx_default_qcnl.conf",]
isvprodid = 0
isvsvn = 0
require_avx = false
require_avx512 = false
require_mpx = false
require_pkru = false
require_amx = false
support_exinfo = false
nonpie_binary = false
enable_stats = false
[[sgx.trusted_files]]
uri = "file:/usr/local/lib/x86_64-linux-gnu/gramine/libsysdb.so"

[[sgx.trusted_files]]
uri = "file:client"

[[sgx.trusted_files]]
uri = "file:/usr/local/lib/x86_64-linux-gnu/gramine/runtime/glibc/"

[[sgx.trusted_files]]
uri = "file:/lib/x86_64-linux-gnu/"

[[sgx.trusted_files]]
uri = "file:/usr/lib/x86_64-linux-gnu/"

[loader.env]
LD_LIBRARY_PATH = "/lib:/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu"
RA_TLS_CLIENT_INSIDE_SGX = "1"
LC_ALL = "C"

```
## Steps to reproduce
```bash
cd CI-Examples/ra-tls-mbedtls 
make clean; make app dcap 
gramine-sgx ./server dcap &
RA_TLS_ALLOW_DEBUG_ENCLAVE_INSECURE=1 RA_TLS_ALLOW_OUTDATED_TCB_INSECURE=1 gramine-sgx \
    ./client_dcap dcap \
    1234567890123456789012345678901234567890123456789012345678901234 \
    1234567890123456789012345678901234567890123456789012345678901234 \
    0 0
```

## Gramine commit hash
Current master: f34f093cdc781a25d9fb4b27a7b5149b616e0da8
Build with: `meson setup build/ --buildtype=release -Ddirect=enabled -Dsgx=enabled  -Ddcap=enabled`
